### ISSUE TITLE
Some bugs in the Demo of the latest DOWNLOAD SCRIPT.

### ISSUE THREAD

**Issue by vrbvillor** [liabru/matter-tools#1]
When the demo select changs to "Chains" or "Bridge" or "Cloth", the console.log shows error "Body.nextGroup" is not a function on Demo.js 677(chains) or line 714(bridge) or line 1203(cloth)...
The "Time scale" demo is not the same as the one on your website.  The shapes disappear....
The "Ray casting" demo shows error Bodies.fromVertices is not a function on line 1480

More ,  please release the instructions of the options of shapes.  Such as champfer:{radius:r}, it's not in the API,  but can be found in demo.js...

And the function name in demo.js is not the same as the select options in the page...

But ,  matter.js is so awesome,  especially the "cloth" and "softbodies"

**Comment by liabru** [comment]
Closed as this is no longer relevant.
