### ISSUE TITLE
The text and background of example select  mixed.

### ISSUE THREAD

**Issue by ChenRenault** [liabru/matter-tools#6]
![image](https://user-images.githubusercontent.com/8744395/36545426-ce878cd4-1823-11e8-8e54-53864e5a7a27.png)
It maybe file:matter-tools/src/styles/demo.css
`.matter-select {
  background: transparent;
...
}
`

**Comment by liabru** [comment]
Thanks for reminding me of this, looks to be covered by #5, please refer to that thread.

**Comment by ChenRenault** [comment]
Okay, I got it, sorry for having not noticed the same issue  :p。
